name = "tb"
filepath = name+".data"
targetpath = name+".txt"
target = open(targetpath, "w")


datafile = open(filepath, 'r')
i = 0
ch1 = datafile.read(1)
ch2 = datafile.read(1)
ch3 = datafile.read(1)
ch4 = datafile.read(1)
ch5 = datafile.read(1)
ch6 = datafile.read(1)
ch7 = datafile.read(1)
ch8 = datafile.read(1)
ch9 = datafile.read(1)
ch10 = datafile.read(1)
ch11 = datafile.read(1)
ch12 = datafile.read(1)
ch13 = datafile.read(1)
ch14 = datafile.read(1)
ch15 = datafile.read(1)
ch16 = datafile.read(1)

target.write("initial begin")
target.write("\n") 
while ch16:
    target.write("    `ITCM.mem_r[%d]=64'h" %i)
    #target.write("    mem_r[%d]=64'h" %i)
    target.write (ch15)
    target.write (ch16)
    target.write (ch13)
    target.write (ch14)
    target.write (ch11)
    target.write (ch12)
    target.write (ch9)
    target.write (ch10)
    target.write (ch7)
    target.write (ch8)
    target.write (ch5)
    target.write (ch6)
    target.write (ch3)
    target.write (ch4)
    target.write (ch1)
    target.write (ch2)
    target.write (";")
    target.write("\n") 
    i=i+1
    ch = datafile.read(1)
    ch1 = datafile.read(1)
    ch2 = datafile.read(1)
    ch3 = datafile.read(1)
    ch4 = datafile.read(1)
    ch5 = datafile.read(1)
    ch6 = datafile.read(1)
    ch7 = datafile.read(1)
    ch8 = datafile.read(1)
    ch9 = datafile.read(1)
    ch10 = datafile.read(1)
    ch11 = datafile.read(1)
    ch12 = datafile.read(1)
    ch13 = datafile.read(1)
    ch14 = datafile.read(1)
    ch15 = datafile.read(1)
    ch16 = datafile.read(1)
target.write ("end\n")
datafile.close()