################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../application/mapper/InfoNES_Mapper.cpp \
../application/mapper/InfoNES_Mapper_000.cpp \
../application/mapper/InfoNES_Mapper_001.cpp \
../application/mapper/InfoNES_Mapper_002.cpp \
../application/mapper/InfoNES_Mapper_003.cpp \
../application/mapper/InfoNES_Mapper_004.cpp \
../application/mapper/InfoNES_Mapper_005.cpp \
../application/mapper/InfoNES_Mapper_006.cpp \
../application/mapper/InfoNES_Mapper_007.cpp \
../application/mapper/InfoNES_Mapper_008.cpp \
../application/mapper/InfoNES_Mapper_009.cpp \
../application/mapper/InfoNES_Mapper_010.cpp \
../application/mapper/InfoNES_Mapper_011.cpp \
../application/mapper/InfoNES_Mapper_013.cpp \
../application/mapper/InfoNES_Mapper_015.cpp \
../application/mapper/InfoNES_Mapper_016.cpp \
../application/mapper/InfoNES_Mapper_017.cpp \
../application/mapper/InfoNES_Mapper_018.cpp \
../application/mapper/InfoNES_Mapper_019.cpp \
../application/mapper/InfoNES_Mapper_021.cpp \
../application/mapper/InfoNES_Mapper_022.cpp \
../application/mapper/InfoNES_Mapper_023.cpp \
../application/mapper/InfoNES_Mapper_024.cpp \
../application/mapper/InfoNES_Mapper_025.cpp \
../application/mapper/InfoNES_Mapper_026.cpp \
../application/mapper/InfoNES_Mapper_032.cpp \
../application/mapper/InfoNES_Mapper_033.cpp \
../application/mapper/InfoNES_Mapper_034.cpp \
../application/mapper/InfoNES_Mapper_040.cpp \
../application/mapper/InfoNES_Mapper_041.cpp \
../application/mapper/InfoNES_Mapper_042.cpp \
../application/mapper/InfoNES_Mapper_043.cpp \
../application/mapper/InfoNES_Mapper_044.cpp \
../application/mapper/InfoNES_Mapper_045.cpp \
../application/mapper/InfoNES_Mapper_046.cpp \
../application/mapper/InfoNES_Mapper_047.cpp \
../application/mapper/InfoNES_Mapper_048.cpp \
../application/mapper/InfoNES_Mapper_049.cpp \
../application/mapper/InfoNES_Mapper_050.cpp \
../application/mapper/InfoNES_Mapper_051.cpp \
../application/mapper/InfoNES_Mapper_057.cpp \
../application/mapper/InfoNES_Mapper_058.cpp \
../application/mapper/InfoNES_Mapper_060.cpp \
../application/mapper/InfoNES_Mapper_061.cpp \
../application/mapper/InfoNES_Mapper_062.cpp \
../application/mapper/InfoNES_Mapper_064.cpp \
../application/mapper/InfoNES_Mapper_065.cpp \
../application/mapper/InfoNES_Mapper_066.cpp \
../application/mapper/InfoNES_Mapper_067.cpp \
../application/mapper/InfoNES_Mapper_068.cpp \
../application/mapper/InfoNES_Mapper_069.cpp \
../application/mapper/InfoNES_Mapper_070.cpp \
../application/mapper/InfoNES_Mapper_071.cpp \
../application/mapper/InfoNES_Mapper_072.cpp \
../application/mapper/InfoNES_Mapper_073.cpp \
../application/mapper/InfoNES_Mapper_074.cpp \
../application/mapper/InfoNES_Mapper_075.cpp \
../application/mapper/InfoNES_Mapper_076.cpp \
../application/mapper/InfoNES_Mapper_077.cpp \
../application/mapper/InfoNES_Mapper_078.cpp \
../application/mapper/InfoNES_Mapper_079.cpp \
../application/mapper/InfoNES_Mapper_080.cpp \
../application/mapper/InfoNES_Mapper_082.cpp \
../application/mapper/InfoNES_Mapper_083.cpp \
../application/mapper/InfoNES_Mapper_085.cpp \
../application/mapper/InfoNES_Mapper_086.cpp \
../application/mapper/InfoNES_Mapper_087.cpp \
../application/mapper/InfoNES_Mapper_088.cpp \
../application/mapper/InfoNES_Mapper_089.cpp \
../application/mapper/InfoNES_Mapper_090.cpp \
../application/mapper/InfoNES_Mapper_091.cpp \
../application/mapper/InfoNES_Mapper_092.cpp \
../application/mapper/InfoNES_Mapper_093.cpp \
../application/mapper/InfoNES_Mapper_094.cpp \
../application/mapper/InfoNES_Mapper_095.cpp \
../application/mapper/InfoNES_Mapper_096.cpp \
../application/mapper/InfoNES_Mapper_097.cpp \
../application/mapper/InfoNES_Mapper_099.cpp \
../application/mapper/InfoNES_Mapper_100.cpp \
../application/mapper/InfoNES_Mapper_101.cpp \
../application/mapper/InfoNES_Mapper_105.cpp \
../application/mapper/InfoNES_Mapper_107.cpp \
../application/mapper/InfoNES_Mapper_108.cpp \
../application/mapper/InfoNES_Mapper_109.cpp \
../application/mapper/InfoNES_Mapper_110.cpp \
../application/mapper/InfoNES_Mapper_112.cpp \
../application/mapper/InfoNES_Mapper_113.cpp \
../application/mapper/InfoNES_Mapper_114.cpp \
../application/mapper/InfoNES_Mapper_115.cpp \
../application/mapper/InfoNES_Mapper_116.cpp \
../application/mapper/InfoNES_Mapper_117.cpp \
../application/mapper/InfoNES_Mapper_118.cpp \
../application/mapper/InfoNES_Mapper_119.cpp \
../application/mapper/InfoNES_Mapper_122.cpp \
../application/mapper/InfoNES_Mapper_133.cpp \
../application/mapper/InfoNES_Mapper_134.cpp \
../application/mapper/InfoNES_Mapper_135.cpp \
../application/mapper/InfoNES_Mapper_140.cpp \
../application/mapper/InfoNES_Mapper_151.cpp \
../application/mapper/InfoNES_Mapper_160.cpp \
../application/mapper/InfoNES_Mapper_180.cpp \
../application/mapper/InfoNES_Mapper_181.cpp \
../application/mapper/InfoNES_Mapper_182.cpp \
../application/mapper/InfoNES_Mapper_183.cpp \
../application/mapper/InfoNES_Mapper_185.cpp \
../application/mapper/InfoNES_Mapper_187.cpp \
../application/mapper/InfoNES_Mapper_188.cpp \
../application/mapper/InfoNES_Mapper_189.cpp \
../application/mapper/InfoNES_Mapper_191.cpp \
../application/mapper/InfoNES_Mapper_193.cpp \
../application/mapper/InfoNES_Mapper_194.cpp \
../application/mapper/InfoNES_Mapper_200.cpp \
../application/mapper/InfoNES_Mapper_201.cpp \
../application/mapper/InfoNES_Mapper_202.cpp \
../application/mapper/InfoNES_Mapper_222.cpp \
../application/mapper/InfoNES_Mapper_225.cpp \
../application/mapper/InfoNES_Mapper_226.cpp \
../application/mapper/InfoNES_Mapper_227.cpp \
../application/mapper/InfoNES_Mapper_228.cpp \
../application/mapper/InfoNES_Mapper_229.cpp \
../application/mapper/InfoNES_Mapper_230.cpp \
../application/mapper/InfoNES_Mapper_231.cpp \
../application/mapper/InfoNES_Mapper_232.cpp \
../application/mapper/InfoNES_Mapper_233.cpp \
../application/mapper/InfoNES_Mapper_234.cpp \
../application/mapper/InfoNES_Mapper_235.cpp \
../application/mapper/InfoNES_Mapper_236.cpp \
../application/mapper/InfoNES_Mapper_240.cpp \
../application/mapper/InfoNES_Mapper_241.cpp \
../application/mapper/InfoNES_Mapper_242.cpp \
../application/mapper/InfoNES_Mapper_243.cpp \
../application/mapper/InfoNES_Mapper_244.cpp \
../application/mapper/InfoNES_Mapper_245.cpp \
../application/mapper/InfoNES_Mapper_246.cpp \
../application/mapper/InfoNES_Mapper_248.cpp \
../application/mapper/InfoNES_Mapper_249.cpp \
../application/mapper/InfoNES_Mapper_251.cpp \
../application/mapper/InfoNES_Mapper_252.cpp \
../application/mapper/InfoNES_Mapper_255.cpp 

OBJS += \
./application/mapper/InfoNES_Mapper.o \
./application/mapper/InfoNES_Mapper_000.o \
./application/mapper/InfoNES_Mapper_001.o \
./application/mapper/InfoNES_Mapper_002.o \
./application/mapper/InfoNES_Mapper_003.o \
./application/mapper/InfoNES_Mapper_004.o \
./application/mapper/InfoNES_Mapper_005.o \
./application/mapper/InfoNES_Mapper_006.o \
./application/mapper/InfoNES_Mapper_007.o \
./application/mapper/InfoNES_Mapper_008.o \
./application/mapper/InfoNES_Mapper_009.o \
./application/mapper/InfoNES_Mapper_010.o \
./application/mapper/InfoNES_Mapper_011.o \
./application/mapper/InfoNES_Mapper_013.o \
./application/mapper/InfoNES_Mapper_015.o \
./application/mapper/InfoNES_Mapper_016.o \
./application/mapper/InfoNES_Mapper_017.o \
./application/mapper/InfoNES_Mapper_018.o \
./application/mapper/InfoNES_Mapper_019.o \
./application/mapper/InfoNES_Mapper_021.o \
./application/mapper/InfoNES_Mapper_022.o \
./application/mapper/InfoNES_Mapper_023.o \
./application/mapper/InfoNES_Mapper_024.o \
./application/mapper/InfoNES_Mapper_025.o \
./application/mapper/InfoNES_Mapper_026.o \
./application/mapper/InfoNES_Mapper_032.o \
./application/mapper/InfoNES_Mapper_033.o \
./application/mapper/InfoNES_Mapper_034.o \
./application/mapper/InfoNES_Mapper_040.o \
./application/mapper/InfoNES_Mapper_041.o \
./application/mapper/InfoNES_Mapper_042.o \
./application/mapper/InfoNES_Mapper_043.o \
./application/mapper/InfoNES_Mapper_044.o \
./application/mapper/InfoNES_Mapper_045.o \
./application/mapper/InfoNES_Mapper_046.o \
./application/mapper/InfoNES_Mapper_047.o \
./application/mapper/InfoNES_Mapper_048.o \
./application/mapper/InfoNES_Mapper_049.o \
./application/mapper/InfoNES_Mapper_050.o \
./application/mapper/InfoNES_Mapper_051.o \
./application/mapper/InfoNES_Mapper_057.o \
./application/mapper/InfoNES_Mapper_058.o \
./application/mapper/InfoNES_Mapper_060.o \
./application/mapper/InfoNES_Mapper_061.o \
./application/mapper/InfoNES_Mapper_062.o \
./application/mapper/InfoNES_Mapper_064.o \
./application/mapper/InfoNES_Mapper_065.o \
./application/mapper/InfoNES_Mapper_066.o \
./application/mapper/InfoNES_Mapper_067.o \
./application/mapper/InfoNES_Mapper_068.o \
./application/mapper/InfoNES_Mapper_069.o \
./application/mapper/InfoNES_Mapper_070.o \
./application/mapper/InfoNES_Mapper_071.o \
./application/mapper/InfoNES_Mapper_072.o \
./application/mapper/InfoNES_Mapper_073.o \
./application/mapper/InfoNES_Mapper_074.o \
./application/mapper/InfoNES_Mapper_075.o \
./application/mapper/InfoNES_Mapper_076.o \
./application/mapper/InfoNES_Mapper_077.o \
./application/mapper/InfoNES_Mapper_078.o \
./application/mapper/InfoNES_Mapper_079.o \
./application/mapper/InfoNES_Mapper_080.o \
./application/mapper/InfoNES_Mapper_082.o \
./application/mapper/InfoNES_Mapper_083.o \
./application/mapper/InfoNES_Mapper_085.o \
./application/mapper/InfoNES_Mapper_086.o \
./application/mapper/InfoNES_Mapper_087.o \
./application/mapper/InfoNES_Mapper_088.o \
./application/mapper/InfoNES_Mapper_089.o \
./application/mapper/InfoNES_Mapper_090.o \
./application/mapper/InfoNES_Mapper_091.o \
./application/mapper/InfoNES_Mapper_092.o \
./application/mapper/InfoNES_Mapper_093.o \
./application/mapper/InfoNES_Mapper_094.o \
./application/mapper/InfoNES_Mapper_095.o \
./application/mapper/InfoNES_Mapper_096.o \
./application/mapper/InfoNES_Mapper_097.o \
./application/mapper/InfoNES_Mapper_099.o \
./application/mapper/InfoNES_Mapper_100.o \
./application/mapper/InfoNES_Mapper_101.o \
./application/mapper/InfoNES_Mapper_105.o \
./application/mapper/InfoNES_Mapper_107.o \
./application/mapper/InfoNES_Mapper_108.o \
./application/mapper/InfoNES_Mapper_109.o \
./application/mapper/InfoNES_Mapper_110.o \
./application/mapper/InfoNES_Mapper_112.o \
./application/mapper/InfoNES_Mapper_113.o \
./application/mapper/InfoNES_Mapper_114.o \
./application/mapper/InfoNES_Mapper_115.o \
./application/mapper/InfoNES_Mapper_116.o \
./application/mapper/InfoNES_Mapper_117.o \
./application/mapper/InfoNES_Mapper_118.o \
./application/mapper/InfoNES_Mapper_119.o \
./application/mapper/InfoNES_Mapper_122.o \
./application/mapper/InfoNES_Mapper_133.o \
./application/mapper/InfoNES_Mapper_134.o \
./application/mapper/InfoNES_Mapper_135.o \
./application/mapper/InfoNES_Mapper_140.o \
./application/mapper/InfoNES_Mapper_151.o \
./application/mapper/InfoNES_Mapper_160.o \
./application/mapper/InfoNES_Mapper_180.o \
./application/mapper/InfoNES_Mapper_181.o \
./application/mapper/InfoNES_Mapper_182.o \
./application/mapper/InfoNES_Mapper_183.o \
./application/mapper/InfoNES_Mapper_185.o \
./application/mapper/InfoNES_Mapper_187.o \
./application/mapper/InfoNES_Mapper_188.o \
./application/mapper/InfoNES_Mapper_189.o \
./application/mapper/InfoNES_Mapper_191.o \
./application/mapper/InfoNES_Mapper_193.o \
./application/mapper/InfoNES_Mapper_194.o \
./application/mapper/InfoNES_Mapper_200.o \
./application/mapper/InfoNES_Mapper_201.o \
./application/mapper/InfoNES_Mapper_202.o \
./application/mapper/InfoNES_Mapper_222.o \
./application/mapper/InfoNES_Mapper_225.o \
./application/mapper/InfoNES_Mapper_226.o \
./application/mapper/InfoNES_Mapper_227.o \
./application/mapper/InfoNES_Mapper_228.o \
./application/mapper/InfoNES_Mapper_229.o \
./application/mapper/InfoNES_Mapper_230.o \
./application/mapper/InfoNES_Mapper_231.o \
./application/mapper/InfoNES_Mapper_232.o \
./application/mapper/InfoNES_Mapper_233.o \
./application/mapper/InfoNES_Mapper_234.o \
./application/mapper/InfoNES_Mapper_235.o \
./application/mapper/InfoNES_Mapper_236.o \
./application/mapper/InfoNES_Mapper_240.o \
./application/mapper/InfoNES_Mapper_241.o \
./application/mapper/InfoNES_Mapper_242.o \
./application/mapper/InfoNES_Mapper_243.o \
./application/mapper/InfoNES_Mapper_244.o \
./application/mapper/InfoNES_Mapper_245.o \
./application/mapper/InfoNES_Mapper_246.o \
./application/mapper/InfoNES_Mapper_248.o \
./application/mapper/InfoNES_Mapper_249.o \
./application/mapper/InfoNES_Mapper_251.o \
./application/mapper/InfoNES_Mapper_252.o \
./application/mapper/InfoNES_Mapper_255.o 

CPP_DEPS += \
./application/mapper/InfoNES_Mapper.d \
./application/mapper/InfoNES_Mapper_000.d \
./application/mapper/InfoNES_Mapper_001.d \
./application/mapper/InfoNES_Mapper_002.d \
./application/mapper/InfoNES_Mapper_003.d \
./application/mapper/InfoNES_Mapper_004.d \
./application/mapper/InfoNES_Mapper_005.d \
./application/mapper/InfoNES_Mapper_006.d \
./application/mapper/InfoNES_Mapper_007.d \
./application/mapper/InfoNES_Mapper_008.d \
./application/mapper/InfoNES_Mapper_009.d \
./application/mapper/InfoNES_Mapper_010.d \
./application/mapper/InfoNES_Mapper_011.d \
./application/mapper/InfoNES_Mapper_013.d \
./application/mapper/InfoNES_Mapper_015.d \
./application/mapper/InfoNES_Mapper_016.d \
./application/mapper/InfoNES_Mapper_017.d \
./application/mapper/InfoNES_Mapper_018.d \
./application/mapper/InfoNES_Mapper_019.d \
./application/mapper/InfoNES_Mapper_021.d \
./application/mapper/InfoNES_Mapper_022.d \
./application/mapper/InfoNES_Mapper_023.d \
./application/mapper/InfoNES_Mapper_024.d \
./application/mapper/InfoNES_Mapper_025.d \
./application/mapper/InfoNES_Mapper_026.d \
./application/mapper/InfoNES_Mapper_032.d \
./application/mapper/InfoNES_Mapper_033.d \
./application/mapper/InfoNES_Mapper_034.d \
./application/mapper/InfoNES_Mapper_040.d \
./application/mapper/InfoNES_Mapper_041.d \
./application/mapper/InfoNES_Mapper_042.d \
./application/mapper/InfoNES_Mapper_043.d \
./application/mapper/InfoNES_Mapper_044.d \
./application/mapper/InfoNES_Mapper_045.d \
./application/mapper/InfoNES_Mapper_046.d \
./application/mapper/InfoNES_Mapper_047.d \
./application/mapper/InfoNES_Mapper_048.d \
./application/mapper/InfoNES_Mapper_049.d \
./application/mapper/InfoNES_Mapper_050.d \
./application/mapper/InfoNES_Mapper_051.d \
./application/mapper/InfoNES_Mapper_057.d \
./application/mapper/InfoNES_Mapper_058.d \
./application/mapper/InfoNES_Mapper_060.d \
./application/mapper/InfoNES_Mapper_061.d \
./application/mapper/InfoNES_Mapper_062.d \
./application/mapper/InfoNES_Mapper_064.d \
./application/mapper/InfoNES_Mapper_065.d \
./application/mapper/InfoNES_Mapper_066.d \
./application/mapper/InfoNES_Mapper_067.d \
./application/mapper/InfoNES_Mapper_068.d \
./application/mapper/InfoNES_Mapper_069.d \
./application/mapper/InfoNES_Mapper_070.d \
./application/mapper/InfoNES_Mapper_071.d \
./application/mapper/InfoNES_Mapper_072.d \
./application/mapper/InfoNES_Mapper_073.d \
./application/mapper/InfoNES_Mapper_074.d \
./application/mapper/InfoNES_Mapper_075.d \
./application/mapper/InfoNES_Mapper_076.d \
./application/mapper/InfoNES_Mapper_077.d \
./application/mapper/InfoNES_Mapper_078.d \
./application/mapper/InfoNES_Mapper_079.d \
./application/mapper/InfoNES_Mapper_080.d \
./application/mapper/InfoNES_Mapper_082.d \
./application/mapper/InfoNES_Mapper_083.d \
./application/mapper/InfoNES_Mapper_085.d \
./application/mapper/InfoNES_Mapper_086.d \
./application/mapper/InfoNES_Mapper_087.d \
./application/mapper/InfoNES_Mapper_088.d \
./application/mapper/InfoNES_Mapper_089.d \
./application/mapper/InfoNES_Mapper_090.d \
./application/mapper/InfoNES_Mapper_091.d \
./application/mapper/InfoNES_Mapper_092.d \
./application/mapper/InfoNES_Mapper_093.d \
./application/mapper/InfoNES_Mapper_094.d \
./application/mapper/InfoNES_Mapper_095.d \
./application/mapper/InfoNES_Mapper_096.d \
./application/mapper/InfoNES_Mapper_097.d \
./application/mapper/InfoNES_Mapper_099.d \
./application/mapper/InfoNES_Mapper_100.d \
./application/mapper/InfoNES_Mapper_101.d \
./application/mapper/InfoNES_Mapper_105.d \
./application/mapper/InfoNES_Mapper_107.d \
./application/mapper/InfoNES_Mapper_108.d \
./application/mapper/InfoNES_Mapper_109.d \
./application/mapper/InfoNES_Mapper_110.d \
./application/mapper/InfoNES_Mapper_112.d \
./application/mapper/InfoNES_Mapper_113.d \
./application/mapper/InfoNES_Mapper_114.d \
./application/mapper/InfoNES_Mapper_115.d \
./application/mapper/InfoNES_Mapper_116.d \
./application/mapper/InfoNES_Mapper_117.d \
./application/mapper/InfoNES_Mapper_118.d \
./application/mapper/InfoNES_Mapper_119.d \
./application/mapper/InfoNES_Mapper_122.d \
./application/mapper/InfoNES_Mapper_133.d \
./application/mapper/InfoNES_Mapper_134.d \
./application/mapper/InfoNES_Mapper_135.d \
./application/mapper/InfoNES_Mapper_140.d \
./application/mapper/InfoNES_Mapper_151.d \
./application/mapper/InfoNES_Mapper_160.d \
./application/mapper/InfoNES_Mapper_180.d \
./application/mapper/InfoNES_Mapper_181.d \
./application/mapper/InfoNES_Mapper_182.d \
./application/mapper/InfoNES_Mapper_183.d \
./application/mapper/InfoNES_Mapper_185.d \
./application/mapper/InfoNES_Mapper_187.d \
./application/mapper/InfoNES_Mapper_188.d \
./application/mapper/InfoNES_Mapper_189.d \
./application/mapper/InfoNES_Mapper_191.d \
./application/mapper/InfoNES_Mapper_193.d \
./application/mapper/InfoNES_Mapper_194.d \
./application/mapper/InfoNES_Mapper_200.d \
./application/mapper/InfoNES_Mapper_201.d \
./application/mapper/InfoNES_Mapper_202.d \
./application/mapper/InfoNES_Mapper_222.d \
./application/mapper/InfoNES_Mapper_225.d \
./application/mapper/InfoNES_Mapper_226.d \
./application/mapper/InfoNES_Mapper_227.d \
./application/mapper/InfoNES_Mapper_228.d \
./application/mapper/InfoNES_Mapper_229.d \
./application/mapper/InfoNES_Mapper_230.d \
./application/mapper/InfoNES_Mapper_231.d \
./application/mapper/InfoNES_Mapper_232.d \
./application/mapper/InfoNES_Mapper_233.d \
./application/mapper/InfoNES_Mapper_234.d \
./application/mapper/InfoNES_Mapper_235.d \
./application/mapper/InfoNES_Mapper_236.d \
./application/mapper/InfoNES_Mapper_240.d \
./application/mapper/InfoNES_Mapper_241.d \
./application/mapper/InfoNES_Mapper_242.d \
./application/mapper/InfoNES_Mapper_243.d \
./application/mapper/InfoNES_Mapper_244.d \
./application/mapper/InfoNES_Mapper_245.d \
./application/mapper/InfoNES_Mapper_246.d \
./application/mapper/InfoNES_Mapper_248.d \
./application/mapper/InfoNES_Mapper_249.d \
./application/mapper/InfoNES_Mapper_251.d \
./application/mapper/InfoNES_Mapper_252.d \
./application/mapper/InfoNES_Mapper_255.d 


# Each subdirectory must supply rules for building sources it contributes
application/mapper/%.o: ../application/mapper/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C++ Compiler'
	riscv-nuclei-elf-g++ -march=rv32imac -mabi=ilp32 -mcmodel=medany -mno-save-restore -O2 -ffunction-sections -fdata-sections -fno-common --specs=nano.specs --specs=nosys.specs  -g -D__IDE_RV_CORE=e203 -DSOC_HBIRD -DDOWNLOAD_MODE=DOWNLOAD_MODE_ILM -DDOWNLOAD_MODE_STRING=\"ILM\" -DBOARD_DDR200T -I"C:\NucleiStudio_workspace\HBirdv2_Prj\nes_test\hbird_sdk\NMSIS\Core\Include" -I"C:\NucleiStudio_workspace\HBirdv2_Prj\nes_test\hbird_sdk\SoC\hbirdv2\Common\Include" -I"C:\NucleiStudio_workspace\HBirdv2_Prj\nes_test\hbird_sdk\SoC\hbirdv2\Board\ddr200t\Include" -I"C:\NucleiStudio_workspace\HBirdv2_Prj\nes_test\application" -std=gnu++11 -fabi-version=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


